services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: trivia_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password_seguro
      POSTGRES_DB: trivia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  # Backend (NestJS)
  backend:
    build:
      context: ./trivia-backend
      dockerfile: Dockerfile
    container_name: trivia_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: tu_password_seguro
      DB_NAME: trivia_db
      JWT_SECRET: clave_secreta_jwt
      FRONT_URL: http://localhost:3001
      ADMIN_EMAIL: admin
      ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - trivia_network


# Volúmenes para persistencia de datos
volumes:
  postgres_data:


